// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cohixczdqcxhnmwcwywi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvaGl4Y3pkcWN4aG5td2N3eXdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDEwNzYsImV4cCI6MjA2NjQ3NzA3Nn0.5NYcJJgNV_exJFaJnLQxJI9tQehjZV1k1zbbwlobCBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);